package com.onlycare.app.utils

/**
 * Agora Configuration
 * 
 * Configuration constants for Agora real-time audio/video communication
 */
object AgoraConfig {
    /**
     * ⚠️ DEPRECATED - App ID is now provided by backend
     * 
     * The Agora App ID is now received from the backend API for each call:
     * - POST /calls/initiate returns agora_app_id
     * - GET /calls/incoming returns agora_app_id
     * - POST /calls/{id}/accept returns agora_app_id
     * 
     * This hardcoded value is ONLY used for diagnostic testing.
     * Production calls use the App ID from the backend.
     */
    @Deprecated("Use App ID from backend API instead", ReplaceWith("Use appId from InitiateCallResponse or IncomingCallDto"))
    const val APP_ID = "63783c2ad2724b839b1e58714bfc2629"  // DIAGNOSTIC TESTING ONLY
    
    /**
     * Default token expiration time (24 hours in seconds)
     * Tokens are generated by backend for security
     */
    const val TOKEN_EXPIRE_TIME = 86400
    
    /**
     * Channel name prefix for calls
     */
    const val CHANNEL_PREFIX = "call_"
}

