<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\User;
use Illuminate\Support\Facades\DB;

class FemaleCreatorsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Sample female creators based on the screenshot
        $creators = [
            [
                'id' => 'USR_' . time() . '001',
                'phone' => '9876500001',
                'country_code' => '+91',
                'name' => 'Ananya798',
                'age' => 24,
                'gender' => 'FEMALE',
                'user_type' => 'FEMALE',
                'profile_image' => 'https://i.pravatar.cc/300?img=1',
                'bio' => 'D. boss all movies',
                'language' => 'Kannada',
                'interests' => json_encode(['Travel', 'Movies', 'Music']),
                'is_online' => true,
                'last_seen' => time(),
                'rating' => 4.5,
                'total_ratings' => 127,
                'coin_balance' => 0,
                'total_earnings' => 5400,
                'audio_call_enabled' => true,
                'video_call_enabled' => true,
                'is_verified' => true,
                'kyc_status' => 'APPROVED',
                'is_blocked' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'USR_' . time() . '002',
                'phone' => '9876500002',
                'country_code' => '+91',
                'name' => 'Nandini043',
                'age' => 22,
                'gender' => 'FEMALE',
                'user_type' => 'FEMALE',
                'profile_image' => 'https://i.pravatar.cc/300?img=5',
                'bio' => 'i like talking',
                'language' => 'Kannada',
                'interests' => json_encode(['Music', 'Dance']),
                'is_online' => false,
                'last_seen' => time() - 3600,
                'rating' => 4.8,
                'total_ratings' => 89,
                'coin_balance' => 0,
                'total_earnings' => 3200,
                'audio_call_enabled' => false,
                'video_call_enabled' => true,
                'is_verified' => true,
                'kyc_status' => 'APPROVED',
                'is_blocked' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'USR_' . time() . '003',
                'phone' => '9876500003',
                'country_code' => '+91',
                'name' => 'Jahnavi1107',
                'age' => 26,
                'gender' => 'FEMALE',
                'user_type' => 'FEMALE',
                'profile_image' => 'https://i.pravatar.cc/300?img=9',
                'bio' => 'Art and creativity enthusiast',
                'language' => 'Kannada',
                'interests' => json_encode(['Art', 'Photography', 'Reading']),
                'is_online' => true,
                'last_seen' => time(),
                'rating' => 4.2,
                'total_ratings' => 45,
                'coin_balance' => 0,
                'total_earnings' => 1800,
                'audio_call_enabled' => true,
                'video_call_enabled' => true,
                'is_verified' => false,
                'kyc_status' => 'PENDING',
                'is_blocked' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'USR_' . time() . '004',
                'phone' => '9876500004',
                'country_code' => '+91',
                'name' => 'Priya_Malayalam',
                'age' => 25,
                'gender' => 'FEMALE',
                'user_type' => 'FEMALE',
                'profile_image' => 'https://i.pravatar.cc/300?img=10',
                'bio' => 'Love chatting and making new friends',
                'language' => 'Malayalam',
                'interests' => json_encode(['Travel', 'Food', 'Movies']),
                'is_online' => true,
                'last_seen' => time(),
                'rating' => 4.7,
                'total_ratings' => 156,
                'coin_balance' => 0,
                'total_earnings' => 6700,
                'audio_call_enabled' => true,
                'video_call_enabled' => true,
                'is_verified' => true,
                'kyc_status' => 'APPROVED',
                'is_blocked' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'USR_' . time() . '005',
                'phone' => '9876500005',
                'country_code' => '+91',
                'name' => 'Divya_Hindi',
                'age' => 23,
                'gender' => 'FEMALE',
                'user_type' => 'FEMALE',
                'profile_image' => 'https://i.pravatar.cc/300?img=16',
                'bio' => 'Bollywood lover and fun conversations',
                'language' => 'Hindi',
                'interests' => json_encode(['Movies', 'Music', 'Dance']),
                'is_online' => true,
                'last_seen' => time(),
                'rating' => 4.6,
                'total_ratings' => 203,
                'coin_balance' => 0,
                'total_earnings' => 8900,
                'audio_call_enabled' => true,
                'video_call_enabled' => true,
                'is_verified' => true,
                'kyc_status' => 'APPROVED',
                'is_blocked' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'USR_' . time() . '006',
                'phone' => '9876500006',
                'country_code' => '+91',
                'name' => 'Lakshmi_Tamil',
                'age' => 27,
                'gender' => 'FEMALE',
                'user_type' => 'FEMALE',
                'profile_image' => 'https://i.pravatar.cc/300?img=20',
                'bio' => 'Love Tamil cinema and meaningful talks',
                'language' => 'Tamil',
                'interests' => json_encode(['Movies', 'Travel', 'Cooking']),
                'is_online' => false,
                'last_seen' => time() - 7200,
                'rating' => 4.4,
                'total_ratings' => 78,
                'coin_balance' => 0,
                'total_earnings' => 2900,
                'audio_call_enabled' => true,
                'video_call_enabled' => false,
                'is_verified' => true,
                'kyc_status' => 'APPROVED',
                'is_blocked' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'USR_' . time() . '007',
                'phone' => '9876500007',
                'country_code' => '+91',
                'name' => 'Keerthi_Telugu',
                'age' => 24,
                'gender' => 'FEMALE',
                'user_type' => 'FEMALE',
                'profile_image' => 'https://i.pravatar.cc/300?img=24',
                'bio' => 'Technology and gadgets enthusiast',
                'language' => 'Telugu',
                'interests' => json_encode(['Technology', 'Gaming', 'Music']),
                'is_online' => true,
                'last_seen' => time(),
                'rating' => 4.9,
                'total_ratings' => 312,
                'coin_balance' => 0,
                'total_earnings' => 12400,
                'audio_call_enabled' => true,
                'video_call_enabled' => true,
                'is_verified' => true,
                'kyc_status' => 'APPROVED',
                'is_blocked' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'USR_' . time() . '008',
                'phone' => '9876500008',
                'country_code' => '+91',
                'name' => 'Arpita_Bengali',
                'age' => 26,
                'gender' => 'FEMALE',
                'user_type' => 'FEMALE',
                'profile_image' => 'https://i.pravatar.cc/300?img=26',
                'bio' => 'Poetry and literature lover',
                'language' => 'Bengali',
                'interests' => json_encode(['Reading', 'Writing', 'Art']),
                'is_online' => false,
                'last_seen' => time() - 1800,
                'rating' => 4.3,
                'total_ratings' => 67,
                'coin_balance' => 0,
                'total_earnings' => 2100,
                'audio_call_enabled' => true,
                'video_call_enabled' => true,
                'is_verified' => false,
                'kyc_status' => 'PENDING',
                'is_blocked' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'USR_' . time() . '009',
                'phone' => '9876500009',
                'country_code' => '+91',
                'name' => 'Sneha_Marathi',
                'age' => 25,
                'gender' => 'FEMALE',
                'user_type' => 'FEMALE',
                'profile_image' => 'https://i.pravatar.cc/300?img=28',
                'bio' => 'Fashion and lifestyle blogger',
                'language' => 'Marathi',
                'interests' => json_encode(['Fashion', 'Travel', 'Photography']),
                'is_online' => true,
                'last_seen' => time(),
                'rating' => 4.5,
                'total_ratings' => 134,
                'coin_balance' => 0,
                'total_earnings' => 5600,
                'audio_call_enabled' => true,
                'video_call_enabled' => true,
                'is_verified' => true,
                'kyc_status' => 'APPROVED',
                'is_blocked' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'USR_' . time() . '010',
                'phone' => '9876500010',
                'country_code' => '+91',
                'name' => 'Reshma_Malayalam',
                'age' => 28,
                'gender' => 'FEMALE',
                'user_type' => 'FEMALE',
                'profile_image' => 'https://i.pravatar.cc/300?img=32',
                'bio' => 'Nature and travel explorer',
                'language' => 'Malayalam',
                'interests' => json_encode(['Travel', 'Nature', 'Photography']),
                'is_online' => true,
                'last_seen' => time(),
                'rating' => 4.8,
                'total_ratings' => 189,
                'coin_balance' => 0,
                'total_earnings' => 7800,
                'audio_call_enabled' => true,
                'video_call_enabled' => true,
                'is_verified' => true,
                'kyc_status' => 'APPROVED',
                'is_blocked' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        // Insert creators
        foreach ($creators as $creator) {
            User::updateOrCreate(
                ['phone' => $creator['phone']], 
                $creator
            );
        }

        $this->command->info('✅ Created ' . count($creators) . ' female creators successfully!');
    }
}







