<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class TestingChecklistSeeder extends Seeder
{
    public function run(): void
    {
        $tests = [
            // 1. AUTHENTICATION & SECURITY (12 Tests)
            ['1.1', 'Authentication & Security', 'Login page loads correctly'],
            ['1.2', 'Authentication & Security', 'Login with valid credentials'],
            ['1.3', 'Authentication & Security', 'Login with invalid email'],
            ['1.4', 'Authentication & Security', 'Login with invalid password'],
            ['1.5', 'Authentication & Security', 'Login with empty fields'],
            ['1.6', 'Authentication & Security', 'Password field is masked'],
            ['1.7', 'Authentication & Security', 'Remember me checkbox'],
            ['1.8', 'Authentication & Security', 'Logout functionality'],
            ['1.9', 'Authentication & Security', 'Session timeout handling'],
            ['1.10', 'Authentication & Security', 'CSRF token validation'],
            ['1.11', 'Authentication & Security', 'Redirect after login'],
            ['1.12', 'Authentication & Security', 'Unauthorized access prevention'],

            // 2. DASHBOARD (15 Tests)
            ['2.1', 'Dashboard', 'Dashboard loads correctly'],
            ['2.2', 'Dashboard', 'Total users stat displays'],
            ['2.3', 'Dashboard', 'Active users stat displays'],
            ['2.4', 'Dashboard', 'Total calls stat displays'],
            ['2.5', 'Dashboard', 'Revenue stat displays'],
            ['2.6', 'Dashboard', 'Quick action: Pending Withdrawals link'],
            ['2.7', 'Dashboard', 'Quick action: KYC Verification link'],
            ['2.8', 'Dashboard', 'Quick action: Pending Reports link'],
            ['2.9', 'Dashboard', 'Recent users table displays'],
            ['2.10', 'Dashboard', 'Recent calls table displays'],
            ['2.11', 'Dashboard', 'View all users link'],
            ['2.12', 'Dashboard', 'View all calls link'],
            ['2.13', 'Dashboard', 'User profile links work'],
            ['2.14', 'Dashboard', 'Dashboard responsive on mobile'],
            ['2.15', 'Dashboard', 'Stats update correctly'],

            // 3. USER MANAGEMENT - LIST VIEW (25 Tests)
            ['3.1', 'User Management - List', 'User list page loads'],
            ['3.2', 'User Management - List', 'Total users stat displays'],
            ['3.3', 'User Management - List', 'Active users stat displays'],
            ['3.4', 'User Management - List', 'Male users stat displays'],
            ['3.5', 'User Management - List', 'Female users stat displays'],
            ['3.6', 'User Management - List', 'User table displays correctly'],
            ['3.7', 'User Management - List', 'User name displays'],
            ['3.8', 'User Management - List', 'User phone displays'],
            ['3.9', 'User Management - List', 'User gender displays'],
            ['3.10', 'User Management - List', 'User status displays'],
            ['3.11', 'User Management - List', 'User KYC status displays'],
            ['3.12', 'User Management - List', 'User coin balance displays'],
            ['3.13', 'User Management - List', 'User joined date displays'],
            ['3.14', 'User Management - List', 'Search by name works'],
            ['3.15', 'User Management - List', 'Search by phone works'],
            ['3.16', 'User Management - List', 'Search by ID works'],
            ['3.17', 'User Management - List', 'Filter by gender: Male'],
            ['3.18', 'User Management - List', 'Filter by gender: Female'],
            ['3.19', 'User Management - List', 'Filter by status: Active'],
            ['3.20', 'User Management - List', 'Filter by status: Blocked'],
            ['3.21', 'User Management - List', 'Filter by KYC: Verified'],
            ['3.22', 'User Management - List', 'Filter by KYC: Pending'],
            ['3.23', 'User Management - List', 'Pagination works'],
            ['3.24', 'User Management - List', 'View user profile link works'],
            ['3.25', 'User Management - List', 'Responsive on mobile'],

            // 4. USER MANAGEMENT - PROFILE VIEW (20 Tests)
            ['4.1', 'User Management - Profile', 'User profile page loads'],
            ['4.2', 'User Management - Profile', 'User avatar/initial displays'],
            ['4.3', 'User Management - Profile', 'User name displays'],
            ['4.4', 'User Management - Profile', 'User phone displays'],
            ['4.5', 'User Management - Profile', 'User status badge displays'],
            ['4.6', 'User Management - Profile', 'Coin balance stat displays'],
            ['4.7', 'User Management - Profile', 'Total calls stat displays'],
            ['4.8', 'User Management - Profile', 'Total earned stat displays'],
            ['4.9', 'User Management - Profile', 'Average rating displays'],
            ['4.10', 'User Management - Profile', 'Basic information section displays'],
            ['4.11', 'User Management - Profile', 'Account status section displays'],
            ['4.12', 'User Management - Profile', 'Recent calls table displays'],
            ['4.13', 'User Management - Profile', 'Recent transactions table displays'],
            ['4.14', 'User Management - Profile', 'Edit user button works'],
            ['4.15', 'User Management - Profile', 'Block user button works'],
            ['4.16', 'User Management - Profile', 'Unblock user button works'],
            ['4.17', 'User Management - Profile', 'Back navigation works'],
            ['4.18', 'User Management - Profile', 'All user fields display correctly'],
            ['4.19', 'User Management - Profile', 'Timestamps format correctly'],
            ['4.20', 'User Management - Profile', 'Responsive on mobile'],

            // 5. USER MANAGEMENT - EDIT VIEW (18 Tests)
            ['5.1', 'User Management - Edit', 'Edit user page loads'],
            ['5.2', 'User Management - Edit', 'Name field pre-filled'],
            ['5.3', 'User Management - Edit', 'Phone field pre-filled'],
            ['5.4', 'User Management - Edit', 'Age field pre-filled'],
            ['5.5', 'User Management - Edit', 'Gender dropdown pre-selected'],
            ['5.6', 'User Management - Edit', 'Language field pre-filled'],
            ['5.7', 'User Management - Edit', 'Coin balance field pre-filled'],
            ['5.8', 'User Management - Edit', 'Bio field pre-filled'],
            ['5.9', 'User Management - Edit', 'Update user with valid data'],
            ['5.10', 'User Management - Edit', 'Update user with invalid data'],
            ['5.11', 'User Management - Edit', 'Name field validation'],
            ['5.12', 'User Management - Edit', 'Phone field validation'],
            ['5.13', 'User Management - Edit', 'Age field validation'],
            ['5.14', 'User Management - Edit', 'Cancel button works'],
            ['5.15', 'User Management - Edit', 'Success message displays'],
            ['5.16', 'User Management - Edit', 'Error messages display'],
            ['5.17', 'User Management - Edit', 'Redirect after update'],
            ['5.18', 'User Management - Edit', 'Responsive on mobile'],

            // 6. CALL MANAGEMENT (22 Tests)
            ['6.1', 'Call Management', 'Call list page loads'],
            ['6.2', 'Call Management', 'Total calls stat displays'],
            ['6.3', 'Call Management', 'Completed calls stat displays'],
            ['6.4', 'Call Management', 'Total duration stat displays'],
            ['6.5', 'Call Management', 'Average duration stat displays'],
            ['6.6', 'Call Management', 'Call table displays'],
            ['6.7', 'Call Management', 'Caller name displays'],
            ['6.8', 'Call Management', 'Receiver name displays'],
            ['6.9', 'Call Management', 'Call type displays'],
            ['6.10', 'Call Management', 'Call status displays'],
            ['6.11', 'Call Management', 'Call duration displays'],
            ['6.12', 'Call Management', 'Call date displays'],
            ['6.13', 'Call Management', 'Search by user name works'],
            ['6.14', 'Call Management', 'Filter by type: Audio'],
            ['6.15', 'Call Management', 'Filter by type: Video'],
            ['6.16', 'Call Management', 'Filter by status: Completed'],
            ['6.17', 'Call Management', 'Filter by status: Missed'],
            ['6.18', 'Call Management', 'Filter by status: Rejected'],
            ['6.19', 'Call Management', 'Filter by status: Cancelled'],
            ['6.20', 'Call Management', 'Pagination works'],
            ['6.21', 'Call Management', 'Duration format correct'],
            ['6.22', 'Call Management', 'Responsive on mobile'],

            // 7. TRANSACTION MANAGEMENT (20 Tests)
            ['7.1', 'Transaction Management', 'Transaction list page loads'],
            ['7.2', 'Transaction Management', 'Total transactions stat displays'],
            ['7.3', 'Transaction Management', 'Total amount stat displays'],
            ['7.4', 'Transaction Management', 'Completed stat displays'],
            ['7.5', 'Transaction Management', 'Pending stat displays'],
            ['7.6', 'Transaction Management', 'Transaction table displays'],
            ['7.7', 'Transaction Management', 'User name displays'],
            ['7.8', 'Transaction Management', 'Transaction type displays'],
            ['7.9', 'Transaction Management', 'Amount displays'],
            ['7.10', 'Transaction Management', 'Coins displays'],
            ['7.11', 'Transaction Management', 'Status displays'],
            ['7.12', 'Transaction Management', 'Date displays'],
            ['7.13', 'Transaction Management', 'Search by user works'],
            ['7.14', 'Transaction Management', 'Filter by type: Purchase'],
            ['7.15', 'Transaction Management', 'Filter by type: Earn'],
            ['7.16', 'Transaction Management', 'Filter by status: Completed'],
            ['7.17', 'Transaction Management', 'Filter by status: Pending'],
            ['7.18', 'Transaction Management', 'Pagination works'],
            ['7.19', 'Transaction Management', 'Amount format correct'],
            ['7.20', 'Transaction Management', 'Responsive on mobile'],

            // 8. WITHDRAWAL MANAGEMENT (22 Tests)
            ['8.1', 'Withdrawal Management', 'Withdrawal list page loads'],
            ['8.2', 'Withdrawal Management', 'Total withdrawals stat displays'],
            ['8.3', 'Withdrawal Management', 'Pending stat displays'],
            ['8.4', 'Withdrawal Management', 'Approved stat displays'],
            ['8.5', 'Withdrawal Management', 'Total amount stat displays'],
            ['8.6', 'Withdrawal Management', 'Withdrawal table displays'],
            ['8.7', 'Withdrawal Management', 'User name displays'],
            ['8.8', 'Withdrawal Management', 'Amount displays'],
            ['8.9', 'Withdrawal Management', 'Bank details display'],
            ['8.10', 'Withdrawal Management', 'Account holder name displays'],
            ['8.11', 'Withdrawal Management', 'Account number displays'],
            ['8.12', 'Withdrawal Management', 'IFSC code displays'],
            ['8.13', 'Withdrawal Management', 'Status displays'],
            ['8.14', 'Withdrawal Management', 'Date displays'],
            ['8.15', 'Withdrawal Management', 'Search by user works'],
            ['8.16', 'Withdrawal Management', 'Filter by status works'],
            ['8.17', 'Withdrawal Management', 'Approve button works'],
            ['8.18', 'Withdrawal Management', 'Reject button works'],
            ['8.19', 'Withdrawal Management', 'Approve button only for pending'],
            ['8.20', 'Withdrawal Management', 'Pagination works'],
            ['8.21', 'Withdrawal Management', 'Amount format correct'],
            ['8.22', 'Withdrawal Management', 'Responsive on mobile'],

            // 9. KYC VERIFICATION (20 Tests)
            ['9.1', 'KYC Verification', 'KYC list page loads'],
            ['9.2', 'KYC Verification', 'Total submissions stat displays'],
            ['9.3', 'KYC Verification', 'Pending stat displays'],
            ['9.4', 'KYC Verification', 'Verified stat displays'],
            ['9.5', 'KYC Verification', 'Rejected stat displays'],
            ['9.6', 'KYC Verification', 'KYC table displays'],
            ['9.7', 'KYC Verification', 'User name displays'],
            ['9.8', 'KYC Verification', 'Document type displays'],
            ['9.9', 'KYC Verification', 'Document number displays'],
            ['9.10', 'KYC Verification', 'Document links display'],
            ['9.11', 'KYC Verification', 'Status displays'],
            ['9.12', 'KYC Verification', 'Date displays'],
            ['9.13', 'KYC Verification', 'Search by user works'],
            ['9.14', 'KYC Verification', 'Filter by status works'],
            ['9.15', 'KYC Verification', 'View front image link works'],
            ['9.16', 'KYC Verification', 'View back image link works'],
            ['9.17', 'KYC Verification', 'Verify button works'],
            ['9.18', 'KYC Verification', 'Reject button works'],
            ['9.19', 'KYC Verification', 'Pagination works'],
            ['9.20', 'KYC Verification', 'Responsive on mobile'],

            // 10. REPORT MANAGEMENT (22 Tests)
            ['10.1', 'Report Management', 'Report list page loads'],
            ['10.2', 'Report Management', 'Total reports stat displays'],
            ['10.3', 'Report Management', 'Pending stat displays'],
            ['10.4', 'Report Management', 'Resolved stat displays'],
            ['10.5', 'Report Management', 'Dismissed stat displays'],
            ['10.6', 'Report Management', 'Report table displays'],
            ['10.7', 'Report Management', 'Reporter name displays'],
            ['10.8', 'Report Management', 'Reported user displays'],
            ['10.9', 'Report Management', 'Report type displays'],
            ['10.10', 'Report Management', 'Reason displays'],
            ['10.11', 'Report Management', 'Status displays'],
            ['10.12', 'Report Management', 'Date displays'],
            ['10.13', 'Report Management', 'Search works'],
            ['10.14', 'Report Management', 'Filter by type works'],
            ['10.15', 'Report Management', 'Filter by status works'],
            ['10.16', 'Report Management', 'Resolve button works'],
            ['10.17', 'Report Management', 'Resolve only for pending/under review'],
            ['10.18', 'Report Management', 'Pagination works'],
            ['10.19', 'Report Management', 'Reason truncates correctly'],
            ['10.20', 'Report Management', 'Type format displays correctly'],
            ['10.21', 'Report Management', 'Status colors correct'],
            ['10.22', 'Report Management', 'Responsive on mobile'],

            // 11. COIN PACKAGE MANAGEMENT (24 Tests)
            ['11.1', 'Coin Package Management', 'Coin packages page loads'],
            ['11.2', 'Coin Package Management', 'Add new package button visible'],
            ['11.3', 'Coin Package Management', 'Package grid displays'],
            ['11.4', 'Coin Package Management', 'Package coin amount displays'],
            ['11.5', 'Coin Package Management', 'Package price displays'],
            ['11.6', 'Coin Package Management', 'Bonus coins display'],
            ['11.7', 'Coin Package Management', 'Description displays'],
            ['11.8', 'Coin Package Management', 'Popular badge displays'],
            ['11.9', 'Coin Package Management', 'Active/Inactive status displays'],
            ['11.10', 'Coin Package Management', 'Edit button works'],
            ['11.11', 'Coin Package Management', 'Delete button works'],
            ['11.12', 'Coin Package Management', 'Delete confirmation works'],
            ['11.13', 'Coin Package Management', 'Create package page loads'],
            ['11.14', 'Coin Package Management', 'Create with valid data works'],
            ['11.15', 'Coin Package Management', 'Coins field validation'],
            ['11.16', 'Coin Package Management', 'Price field validation'],
            ['11.17', 'Coin Package Management', 'Mark as popular checkbox'],
            ['11.18', 'Coin Package Management', 'Active checkbox'],
            ['11.19', 'Coin Package Management', 'Cancel button works'],
            ['11.20', 'Coin Package Management', 'Edit page loads with data'],
            ['11.21', 'Coin Package Management', 'Update package works'],
            ['11.22', 'Coin Package Management', 'Empty state displays'],
            ['11.23', 'Coin Package Management', 'Currency format correct'],
            ['11.24', 'Coin Package Management', 'Responsive on mobile'],

            // 12. APP SETTINGS (25 Tests)
            ['12.1', 'App Settings', 'Settings page loads'],
            ['12.2', 'App Settings', 'Call rate field displays'],
            ['12.3', 'App Settings', 'Video call rate field displays'],
            ['12.4', 'App Settings', 'Welcome bonus field displays'],
            ['12.5', 'App Settings', 'Referral bonus field displays'],
            ['12.6', 'App Settings', 'Coin to INR rate field displays'],
            ['12.7', 'App Settings', 'Min withdrawal amount displays'],
            ['12.8', 'App Settings', 'Max withdrawal amount displays'],
            ['12.9', 'App Settings', 'Withdrawal fee field displays'],
            ['12.10', 'App Settings', 'App name field displays'],
            ['12.11', 'App Settings', 'Support email field displays'],
            ['12.12', 'App Settings', 'Support phone field displays'],
            ['12.13', 'App Settings', 'Maintenance mode checkbox'],
            ['12.14', 'App Settings', 'Update settings works'],
            ['12.15', 'App Settings', 'Call rate validation'],
            ['12.16', 'App Settings', 'Video call rate validation'],
            ['12.17', 'App Settings', 'Welcome bonus validation'],
            ['12.18', 'App Settings', 'Referral bonus validation'],
            ['12.19', 'App Settings', 'Coin rate validation'],
            ['12.20', 'App Settings', 'Min withdrawal validation'],
            ['12.21', 'App Settings', 'Max withdrawal validation'],
            ['12.22', 'App Settings', 'Email validation'],
            ['12.23', 'App Settings', 'Success message displays'],
            ['12.24', 'App Settings', 'Settings persist after save'],
            ['12.25', 'App Settings', 'Responsive on mobile'],

            // 13. NAVIGATION & LAYOUT (15 Tests)
            ['13.1', 'Navigation & Layout', 'Sidebar displays correctly'],
            ['13.2', 'Navigation & Layout', 'Dashboard menu link works'],
            ['13.3', 'Navigation & Layout', 'Users menu link works'],
            ['13.4', 'Navigation & Layout', 'Calls menu link works'],
            ['13.5', 'Navigation & Layout', 'Transactions menu link works'],
            ['13.6', 'Navigation & Layout', 'Withdrawals menu link works'],
            ['13.7', 'Navigation & Layout', 'KYC menu link works'],
            ['13.8', 'Navigation & Layout', 'Reports menu link works'],
            ['13.9', 'Navigation & Layout', 'Coin Packages menu link works'],
            ['13.10', 'Navigation & Layout', 'Settings menu link works'],
            ['13.11', 'Navigation & Layout', 'Active menu item highlights'],
            ['13.12', 'Navigation & Layout', 'Mobile menu toggle works'],
            ['13.13', 'Navigation & Layout', 'Logout button works'],
            ['13.14', 'Navigation & Layout', 'Logo displays correctly'],
            ['13.15', 'Navigation & Layout', 'Sidebar collapses on mobile'],

            // 14. DARK MODE (10 Tests)
            ['14.1', 'Dark Mode', 'Dark mode toggle displays'],
            ['14.2', 'Dark Mode', 'Toggle to dark mode works'],
            ['14.3', 'Dark Mode', 'Toggle to light mode works'],
            ['14.4', 'Dark Mode', 'Dark mode persists after refresh'],
            ['14.5', 'Dark Mode', 'All pages support dark mode'],
            ['14.6', 'Dark Mode', 'Text readable in dark mode'],
            ['14.7', 'Dark Mode', 'Colors consistent in dark mode'],
            ['14.8', 'Dark Mode', 'Forms visible in dark mode'],
            ['14.9', 'Dark Mode', 'Tables readable in dark mode'],
            ['14.10', 'Dark Mode', 'Icons visible in dark mode'],

            // 15. RESPONSIVE DESIGN (10 Tests)
            ['15.1', 'Responsive Design', 'Desktop view (1920x1080)'],
            ['15.2', 'Responsive Design', 'Laptop view (1366x768)'],
            ['15.3', 'Responsive Design', 'Tablet landscape (1024x768)'],
            ['15.4', 'Responsive Design', 'Tablet portrait (768x1024)'],
            ['15.5', 'Responsive Design', 'Mobile landscape (667x375)'],
            ['15.6', 'Responsive Design', 'Mobile portrait (375x667)'],
            ['15.7', 'Responsive Design', 'Small mobile (320x568)'],
            ['15.8', 'Responsive Design', 'Tables scroll on mobile'],
            ['15.9', 'Responsive Design', 'Forms usable on mobile'],
            ['15.10', 'Responsive Design', 'Touch targets adequate'],

            // 16. PERFORMANCE & UX (8 Tests)
            ['16.1', 'Performance & UX', 'Pages load under 3 seconds'],
            ['16.2', 'Performance & UX', 'No JavaScript errors'],
            ['16.3', 'Performance & UX', 'No CSS issues'],
            ['16.4', 'Performance & UX', 'Images load correctly'],
            ['16.5', 'Performance & UX', 'Icons display correctly'],
            ['16.6', 'Performance & UX', 'Smooth transitions'],
            ['16.7', 'Performance & UX', 'No console errors'],
            ['16.8', 'Performance & UX', 'Forms submit smoothly'],
        ];

        foreach ($tests as $test) {
            DB::table('testing_checklist')->insert([
                'test_number' => $test[0],
                'category' => $test[1],
                'test_case' => $test[2],
                'status' => 'Not Tested',
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        }
    }
}







